apiVersion: v1
kind: ConfigMap
metadata:
  name: vitestmart-configmap
data:
  MONGODB_URI: "mongodb+srv://mangeshforstudy_db_user:sNdbqYh89gmYIg8L@cluster0.cukhoit.mongodb.net/?appName=Cluster0"
  PORT: "5000"
