apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitestmart
  labels:
    app: vitestmart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vitestmart
  template:
    metadata:
      labels:
        app: vitestmart
    spec:
      containers:
        - name: vitestmart
          image: mangeshgot/vitestmart:1.0
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: vitestmart-configmap
                  key: MONGODB_URI
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: vitestmart-configmap
                  key: PORT
          ports:
            - containerPort: 5000
