apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitestmart
  labels:
    app: vitestmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vitestmart
  template:
    metadata:
      labels:
        app: vitestmart
    spec:
      containers:
        - name: vitestmart
          image: mangeshgot/vitestmart:1.0
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: NODE_ENV
              value: "production"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: vitestmart-secret
                  key: mongodb-uri
