apiVersion: v1
kind: Secret
metadata:
  name: vitestmart-secret
type: Opaque
stringData:
  mongodb-uri: "mongodb+srv://mangeshforstudy_db_user:sNdbqYh89gmYIg8L@cluster0.cukhoit.mongodb.net/vitestmart?retryWrites=true&w=majority"
