apiVersion: v1
kind: Service
metadata:
  name: vitestmart-service
spec:
  selector:
    app: vitestmart
  ports:
    - protocol: TCP
      port: 80 # Port accessible outside the cluster (LoadBalancer/NodePort)
      targetPort: 5000 # Port the container is listening on
  type: NodePort # Use NodePort if you are on a local cluster like Minikube
